server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://123.56.167.108:3306/mydb01?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: cn.itcast.user.pojo