server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://123.56.167.108:3306/mydb01?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  application:
    name: consumer  #应用名称
mybatis:
  type-aliases-package: cn.itcast.user.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找